# .rubocop.yml
# Rails 8 friendly + auto-correct friendly defaults

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.3
  TargetRailsVersion: 8.0

  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true

  Include:
    - "Rakefile"
    - "config.ru"
    - "Gemfile"
    - "bin/**/*"
    - "app/**/*.rb"
    - "config/**/*.rb"
    - "db/**/*.rb"
    - "lib/**/*.rb"
    - "spec/**/*.rb"

  Exclude:
    - "db/schema.rb"
    - "db/structure.sql"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "public/**/*"
    - "storage/**/*"
    - "tmp/**/*"
    - "log/**/*"
    - "bin/bundle"
    - "bin/rails"
    - "bin/rubocop"
    - "bin/setup"
    - "bin/update"
    - "config/initializers/devise.rb"
    - "config/initializers/simple_form.rb"

Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - '\A\s*#'
  Exclude:
    - "config/routes.rb"

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: percent

Style/WordArray:
  EnforcedStyle: percent

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/RedundantPercentQ:
  Enabled: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/IfUnlessModifier:
  Enabled: true

Style/GuardClause:
  Enabled: true
  MinBodyLength: 1

Style/SafeNavigation:
  Enabled: true

Style/RedundantInterpolation:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

Style/FetchEnvVar:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: true

Style/NumericPredicate:
  Enabled: true

Style/SignalException:
  EnforcedStyle: semantic

Style/HashExcept:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*.rb"

Lint/UnusedMethodArgument:
  Enabled: true
  AllowUnusedKeywordArguments: true
  IgnoreEmptyMethods: true

Metrics/MethodLength:
  Max: 25
  CountComments: false

Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
    - "config/routes.rb"
    - "Rakefile"
    - "*.gemspec"
    - "lib/tasks/**/*.rake"

# ---------------------------
# Rails
# ---------------------------

Rails:
  Enabled: true

Rails/TimeZone:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: true
  AllowedMethods:
    - update_columns
    - update_column
    - touch

Rails/OutputSafety:
  Enabled: true

Rails/FindById:
  Enabled: true

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/InverseOf:
  Enabled: true

Rails/Delegate:
  Enabled: true

Rails/I18nLocaleTexts:
  Enabled: true

# ---------------------------
# Performance
# ---------------------------

Performance:
  Enabled: true

Performance/ChainArrayAllocation:
  Enabled: true

Performance/RedundantMerge:
  Enabled: true

# ---------------------------
# Bundler
# ---------------------------

Bundler/OrderedGems:
  Enabled: false

RSpec:
  Enabled: true

RSpec/ExampleLength:
  Max: 25

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/MessageSpies:
  Enabled: true

# ---------------------------
# Naming
# ---------------------------

Naming/PredicateName:
  Enabled: true
  ForbiddenPrefixes:
    - is_
    - have_

Security:
  Enabled: true