#!/usr/bin/env bash

set -euo pipefail

echo "==> Converting ERB views to HAML..."

# 1. Convert *.html.haml -> *.html.haml
find app/views -name "*.html.haml" | while read -r erb; do
  haml="${erb%.erb}.haml"

  echo "Converting: $erb -> $haml"
  html2haml "$erb" "$haml"

  # Remove original ERB after successful conversion
  rm "$erb"
done

echo "==> ERB conversion completed."

echo
echo "==> Removing autogenerated test files..."

# 2. Remove Rails default test directory (if present)
if [ -d test ]; then
  echo "Removing test/"
  rm -rf test
fi

# 3. Remove unwanted RSpec autogenerated specs
for dir in spec/views spec/helpers spec/controllers; do
  if [ -d "$dir" ]; then
    echo "Removing $dir/"
    rm -rf "$dir"
  fi
done

echo
echo "==> Cleanup completed."
echo "All ERB views converted to HAML and unnecessary tests removed."