# frozen_string_literal: true

# app/jobs/process_run_rollback_job.rb
class ProcessRunRollbackJob < ApplicationJob
  queue_as :default

  # call this before/after destroy:
  # - If the run still exists: just pass run_id
  # - If the run has been deleted: that's okay, as long as you can pass lexeme_processor_id or lexeme_ids for more precision
  #
  # Here we clean based on run_id as the primary key (even if the run is deleted, it doesn't affect cleaning LexemeProcessResult because it has process_run_id)
  def perform(process_run_id:)
    # 1) Find run (might be deleted)
    @run = ProcessRun.find_or_initialize_by(id: process_run_id)

    # 2) Get lexeme_ids related to this run (if run exists, prioritize getting from DB result table)
    lexeme_ids =
      LexemeProcessResult
        .where(process_run_id: process_run_id)
        .distinct
        .pluck(:lexeme_id)

    return if lexeme_ids.blank?

    # 3) Find occurrences corresponding to these lexemes
    occurrence_ids =
      Occurrence
        .where(lexeme_id: lexeme_ids)
        .pluck(:id)

    # 4) Start transaction: ensure rollback consistency
    ApplicationRecord.transaction do
      # Delete process results generated by this run
      LexemeProcessResult.where(process_run_id: process_run_id).delete_all

      # Delete reviews for these occurrences (because review is a single record that overwrites)
      if occurrence_ids.any?
        OccurrenceReview.where(occurrence_id: occurrence_ids).delete_all
      end

      # Restore occurrence statuses
      Occurrence.where(id: occurrence_ids).update_all(status: "unprocessed", updated_at: Time.current) if occurrence_ids.any?

      # Restore lexeme statuses
      Lexeme.where(id: lexeme_ids).update_all(process_status: "pending", updated_at: Time.current)
    end

    # 5) Clear progress cache (if run doesn't exist, can only clean by naming convention)
    clear_progress_cache
  rescue => e
    Rails.logger&.error("[ProcessRunRollbackJob] failed process_run_id=#{process_run_id} err=#{e.class}: #{e.message}")
    raise
  end

  private

  def clear_progress_cache
    keys = [
      @run.batches_total_key,
      @run.batches_done_key,
      @run.finalize_lock_key,
      @run.total_count_key,
      @run.succeed_count_key,
      @run.failed_count_key,
      @run.occ_rev_count_key
    ]
    keys.each { |k| Rails.cache.delete(k) rescue nil }
  end
end